name: family_notes
description: suilog

publish_to: "none"

version: 1.0.3+6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^3.1.2
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  event_bus: ^2.0.0
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.9
  firebase_messaging: ^14.0.4
  fl_chart: ^0.55.2

  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^12.0.3

  flutter_localizations:
    sdk: flutter

  flutter_svg: ^1.1.5
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.2
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.6.0
  keyboard_actions: ^4.1.0
  lottie: ^2.0.0
  package_info_plus: ^1.4.3+1
  pull_to_refresh: ^2.0.0
  reactive_forms: ^14.1.0
  shared_preferences: ^2.0.15
  tab_container: ^2.0.0
  url_launcher: ^6.1.6
  webview_flutter: ^4.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.0.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.3.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/fonts/

  fonts:
    - family: MPLUSRounded
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_Android.png"
  image_path_ios: "assets/images/icon_Ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/adaptive_foreground.png"
